# -*- coding: utf-8 -*-
"""ABBA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VX-OJFE-vS5gDqOKaEJG1JveoTiqcxNP
"""

import re
s = input()
if re.search("(AB.*BA|BA.*AB)", s):
    print("YES")
else:
  print("NO")