# -*- coding: utf-8 -*-
"""age2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HM0B5ed0-DgzYLO3rLZzdpMy-2I3Qyb8
"""

m=0
d=0
x=int(input())
for i in range (10,90):
  x=int(input())
  if x>m:
      d=m
      m=x
  elif x<m and x>d and x!=-1:
   # i=i+1
    d=x
  if x==-1:
    break
print(m , " ", d)