# -*- coding: utf-8 -*-
"""age_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z7S84B9IGvPMBdnTRLLXgLRLF5UzBNzx
"""

m=0
x=int(input())
for i in range (10,90):
  x=int(input())
  if x>m:
      m=x
  else:
    i=i+1
  if x==-1:
    break
print(m)