# -*- coding: utf-8 -*-
"""area

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZTTfG9POnUU2NcRttO0Yx3DM5L9xELyp
"""

length=int(input())
width=int(input())
print(length*width)