# -*- coding: utf-8 -*-
"""competition_kabedi

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xVqw9LatGmNl3IroiMmfrhuLHfe54w2t
"""

n=int(input())
count=0

x=input()
for i in range (0,n):
  ls=x.split()
  ls[i]=int(ls[i])
  if ls[i]==0 or ls[i]==1 or ls[i]==2:
      count+=1

t=count//3
  



print(t)