# -*- coding: utf-8 -*-
"""distance

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lyR4yGCPiJlTwvmwVAb6N7qcW6on3vVp
"""

s=input()

ls=s.split()


ls[0]=int(ls[0])
ls[1]=int(ls[1])
ls[2]=int(ls[2])

ls.sort()

x1=abs(ls[0]-ls[1])
x2=abs(ls[1]-ls[2])

dis=(x1+x2)

print(dis)