# -*- coding: utf-8 -*-
"""countries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15WMPBTfOM7sb9g8AU4k51-qpU6scRzO1
"""

n=int(input())
counter=dict() 

inp=[]

for i in range (0,n):
  s=input()
  inp.append(s)

for i in inp:
  if i in counter:
    counter[i]+=1
  else:
    counter[i]=1


for letter in sorted(counter):
 print(letter,counter[letter])