# -*- coding: utf-8 -*-
"""great_num

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GQJ6_ofhjK_BF_sKpaQo2GTiVydb7wRq
"""

a=int(input())
b=int(input())
if a>b:
  print(a)
elif b>a:
  print(b)
else:
  print (a)