# -*- coding: utf-8 -*-
"""hello

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fFSrogG6GI8IeHro12aPmv6zK9zP3d_
"""

print("Hello World!")