# -*- coding: utf-8 -*-
"""hellosara

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MeaxL1CQOq5OH-MQnnkO_ceiQHKU9-yf
"""

import re

s = input()
remove_characters = ['a','b','c','d','f','g','i','j','k','m','n','p','q','r','s','t','u','v','w','x','y','z']

for character in remove_characters:
    s = s.replace(character, "")

if re.match(r'.*?h[^e]*e[^l]*l[^l]*l[^o]*o',s):
  print ('YES')
else:
  print ('NO')