# -*- coding: utf-8 -*-
"""laptopprice

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_0jiR_akTahR0kFG6V71av__FWX6Evk
"""

def is_irsa_happy(laptops):
  for i in range (len(laptops)):
    for j in range (i+1, len(laptops)):
      if ((laptops[i][0] < laptops[j][0]) and (laptops[i][1] > laptops[j][1])) or ((laptops[i][0] > laptops[j][0]) and (laptops[i][1] < laptops[j][1])):
         return True
 
  return False

count = int(input())

laptops = []
for i in range (count):
 inp = input()
 inp_list = inp.split(' ')
 laptops.append ((int(inp_list[0]), int(inp_list[1])))

if (is_irsa_happy(laptops)):
 print ("happy irsa")
else:
 print ("poor irsa")