# -*- coding: utf-8 -*-
"""maxdiv

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zP-zBQkImEwy_rgfMGkKiTHmPCHG03nu
"""

max_c=0
max_n=0
def divi():
  count=0
  for i in range (1, num+1):
    if num%i==0:
      count+=1
  return count

for i in range (0,20):
  num=int(input())
  if max_c<divi():
    max_c=divi()
    max_n=num

print(max_n,"",max_c)