# -*- coding: utf-8 -*-
"""mazrab10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-2uoLYBXoEROrFb0ZiMEcZCYr4F4-EAV
"""

n=int(input())
n=(n//10)+1
n=n*10
print(n)