# -*- coding: utf-8 -*-
"""plusstring

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16DXB0JmBs8L23e6oshP_9JaAyxm_tYM7
"""

s=input()
for char in s:
  s=s.replace('+','')
  s=s.replace('31','13')
  s=s.replace('21','12')
  s=s.replace('32','23')
  s=s.replace('1','1+')
  s=s.replace('2','2+')
  s=s.replace('3','3+')
  s = s[:-1]


  
 
print(s)