# -*- coding: utf-8 -*-
"""prime

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Mnx9by0ttfbSH7w3Zewi4bh4F0nf5TG
"""

number = int(input())

if number > 1:
    for i in range(2, number):
        if (number % i) == 0:
            print("not prime")
            break
    else:
        print("prime")


else:
    print("not prime")