# -*- coding: utf-8 -*-
"""rev

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hppz_3k21ke33zZfyiGqGiI8IcEtYnMt
"""

x=int(input())
x = int(str(x % 10) + str(x % 100 // 10) + str(x // 100))
rev=2*x
print(rev)