# -*- coding: utf-8 -*-
"""sepidrood

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DxK1oyKtzwfosBwV1x6kunlnmvK5uu1I
"""

count=0
y=0
for i in range (0,30):
  x=int(input())
  y=x+y
  if x==3:
    count+=1
print(y, " ", count)