# -*- coding: utf-8 -*-
"""sqrt

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Ikqne9ZhHoOdJ6cQtOCWDf7awA4xP60
"""

import math

sq=0
s=[]
q=[]

x=int(input())

for i in range (0,x):
  n=int(input())
  s.append(float(n))

for i in s:
  sq=math.sqrt(i)
  q.append(float(sq))

def numberWithoutRounding(num, precision=4):
    [beforeDecimal, afterDecimal] = str(num).split('.')
    return (beforeDecimal + '.' + afterDecimal[0:precision])

for j in range (0,len(s)):
  q[j] = int(q[j]*10000)/10000
  print(numberWithoutRounding("%.4f" % q[j]))