# -*- coding: utf-8 -*-
"""standard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YYSsntRTdRGYaelUQb4ldhx4OoYzIJMy
"""

ip1=input()
ip2=input()
ip3=input()
ip4=input()
ip5=input()
ip6=input()
ip7=input()
ip8=input()
ip9=input()
ip10=input()

def stad(s):
  s=s.lower()
  s=s.capitalize()
  return s
  
print(stad(ip1))
print(stad(ip2))
print(stad(ip3))
print(stad(ip4))
print(stad(ip5))
print(stad(ip6))
print(stad(ip7))
print(stad(ip8))
print(stad(ip9))
print(stad(ip10))