# -*- coding: utf-8 -*-
"""string

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KQt5NFzHQZOL80PhBh5QnG_mvbiucucu
"""

s=input()
s=s.lower()
for char in s:
  s=s.replace('a','')
  s=s.replace('e','')
  s=s.replace('i','')
  s=s.replace('u','')
  s=s.replace('o','')

f_string=''
for char in s:
    f_string += ('.' + char)
print(f_string)