# -*- coding: utf-8 -*-
"""translator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15GZfVutgdgFOzCrW_m78bz8gg_YFF6F5
"""

from collections import OrderedDict

n=int(input())

tr=OrderedDict()
inp=[]

for i in range (0,n):
  w=str(input())
  k=w.split(" ")
  tr[k[0]]=k[1]

sen=input()
sn=sen.split()

s=''
for i in sn:
  if i in tr:
    s = s + tr.get(i) + ' '
  else:
    s=s+i+' '

print(s)