# -*- coding: utf-8 -*-
"""upperlower

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18AnW-ua3Zb535GjUFisxmLRBDf5ln2e4
"""

s = input()

uc=sum(1 for c in s if c.isupper())
lc=sum(1 for c in s if c.islower())

if uc>lc:
  s=s.upper()
else:
  s=s.lower()
print(s)